version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=bi
      - MARIADB_USER=bi
      - MARIADB_DATABASE=bi
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - mariadb
    links:
      - mariadb:db

  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bi
      - DB_DATABASE=bi
      - DB_PASSWORD=bi
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
